import { createHandler as createComparisonHandler } from '../compare-schools/handler.mjs';

export const BASIC_V1_FIELDS = [
  "school_id",
  "school_name",
  "school_name_cn",
  "short_name",
  "institution_control",
  "school_type",
  "city",
  "city_cn",
  "state",
  "state_cn",
  "tuition_fees",
  "tuition_fees_year",
  "coa",
  "coa_year",
  "undergrad_enrollment",
  "undergrad_enrollment_year",
  "applicants",
  "admitted",
  "first_year_enrollment",
  "acceptance_rate",
  "admissions_year",
  "sat_25",
  "sat_75",
  "act_25",
  "act_75",
  "test_policy",
  "test_policy_cycle",
  "international_pct",
  "international_pct_year",
  "international_pct_scope",
  "graduation_rate_4yr",
  "graduation_rate_4yr_year",
  "international_need_aid",
  "international_merit_aid",
  "english_proficiency_policy",
  "english_tests_accepted",
  "english_policy_cycle",
  "ranking_usnews",
  "ranking_category",
  "ranking_year",
  "region",
  "location_cn",
  "ranking_tier",
  "campus_type",
  "campus_description",
  "campus_description_cn",
  "famous_majors",
  "famous_majors_cn",
  "career_model",
  "career_model_cn",
  "notable_alumni"
];

export function createHandler(options) {
  return createComparisonHandler({ ...options, rpcName: 'get_school_comparison_basic_v1', responseFields: BASIC_V1_FIELDS });
}
